# Generated by Django 4.1 on 2022-10-10 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='plantInformation',
            fields=[
                ('scientificName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('localName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('propagation', models.TextField()),
                ('nativeRange', models.TextField()),
                ('invasiveType', models.CharField(choices=[('invasive', 'invasive'), ('exotic', 'exotic')], max_length=10)),
                ('seedlingDispersionRadius', models.IntegerField(default=1000)),
                ('comments', models.TextField()),
                ('control', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tempFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='iasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('reverseGeoLoc', models.TextField()),
                ('seedlingDispersionAffectedAreas', models.TextField(null=True)),
                ('filename', models.CharField(max_length=200)),
                ('filepath', models.TextField()),
                ('requestnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.classifier')),
                ('scientificName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.plantinformation')),
            ],
        ),
    ]
