# Generated by Django 4.1 on 2022-09-04 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plantInformation',
            fields=[
                ('scientificName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('localName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('propagation', models.TextField()),
                ('nativeRange', models.TextField()),
                ('comments', models.TextField()),
                ('control', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('filename', models.CharField(max_length=200)),
                ('scientificName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.plantinformation')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
