# Generated by Django 4.1 on 2022-10-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seedlingDispersionAffectedAreas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='iasdata',
            name='seedlingDispersionAffectedAreas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.seedlingdispersionaffectedareas'),
        ),
    ]
