# Generated by Django 4.1 on 2022-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='longtitude',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
