# Generated by Django 4.1 on 2022-10-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantInformationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('plantInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.plantinformation')),
            ],
        ),
    ]
