# Generated by Django 4.1 on 2022-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinformation',
            name='invasiveType',
            field=models.CharField(choices=[('invasive', 'invasive'), ('exotic', 'exotic')], default='invasive', max_length=10),
            preserve_default=False,
        ),
    ]
