# Generated by Django 4.1 on 2022-10-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_plantinformationimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinformation',
            name='family',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantinformation',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
