# Generated by Django 4.1 on 2022-10-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_seedlingdispersionaffectedareas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iasdata',
            name='seedlingDispersionAffectedAreas',
        ),
        migrations.AddField(
            model_name='seedlingdispersionaffectedareas',
            name='ias_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier.iasdata'),
        ),
    ]
