# Generated by Django 4.1 on 2022-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_plantinformation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinformation',
            name='icon',
            field=models.TextField(default='/static/information/images/marker.png'),
            preserve_default=False,
        ),
    ]
