# Generated by Django 4.1 on 2022-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_classifier_longtitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempFileHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
        ),
    ]
