# Generated by Django 4.1 on 2022-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_plantinformation_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinformation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
