# Generated by Django 4.1 on 2022-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_alter_plantinformationimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iasdata',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
