# Generated by Django 4.1 on 2022-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantreports',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plantreports',
            name='chartdata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
