# Generated by Django 4.1 on 2022-10-26 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_plantreports_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantreports',
            name='data_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantreports',
            name='data_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
