# Generated by Django 4.1 on 2022-10-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_plantreports_data_end_plantreports_data_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantreports',
            old_name='data_end',
            new_name='data_date_end',
        ),
        migrations.RenameField(
            model_name='plantreports',
            old_name='data_start',
            new_name='data_date_start',
        ),
    ]
