# Generated by Django 4.1 on 2022-10-23 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifier', '0004_alter_plantinformationimages_options_and_more'),
        ('accounts', '0002_rename_users_authentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='voteResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=5, null=True)),
                ('iasdata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.iasdata')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
