# Generated by Django 4.1 on 2022-10-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_voteresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='educationalAttainment',
            field=models.CharField(choices=[('bachelor', 'bachelor'), ('masteral', 'masteral'), ('doctorate', 'doctorate')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='proof',
            field=models.TextField(default=None, null=True),
        ),
    ]
