# Generated by Django 4.1 on 2022-10-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_authentication_educationalattainment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresults',
            name='type',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], default=None, max_length=5, null=True),
        ),
    ]
