# Generated by Django 4.1 on 2022-10-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_voteresults_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='educationalAttainment',
            field=models.CharField(choices=[('None', '-----'), ('bachelor', 'bachelor'), ('masteral', 'masteral'), ('doctorate', 'doctorate')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voteresults',
            name='type',
            field=models.CharField(choices=[('None', '-----'), ('up', 'up'), ('down', 'down')], default=None, max_length=5, null=True),
        ),
    ]
