# Generated by Django 4.1 on 2022-10-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_authentication_educationalattainment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='educationalAttainment',
            field=models.CharField(choices=[('None', '-----'), ('bachelor', 'bachelor'), ('masteral', 'masteral'), ('doctorate', 'doctorate')], default='None', max_length=10, null=True),
        ),
    ]
