# Generated by Django 4.1 on 2022-10-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_authentication_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='is_authenticated',
            new_name='is_authenticateds',
        ),
    ]
