# Generated by Django 4.1 on 2022-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_is_authenticated_authentication_is_authenticateds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='is_authenticateds',
            new_name='is_authenticated',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='educationalAttainment',
            field=models.CharField(choices=[('None', '-----'), ('bachelor', 'bachelor'), ('masteral', 'masteral'), ('doctorate', 'doctorate')], default='none', max_length=10, null=True),
        ),
    ]
