# Generated by Django 4.1 on 2022-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_authenticateds_authentication_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='educationalAttainment',
            field=models.CharField(choices=[('None', '-----'), ('bachelor', 'bachelor'), ('masteral', 'masteral'), ('doctorate', 'doctorate')], default=None, max_length=10, null=True),
        ),
    ]
