# Generated by Django 4.1 on 2022-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_authentication_educationalattainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='proof',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
