# Generated by Django 4.1 on 2022-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_authentication_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
