# Generated by Django 4.1 on 2022-10-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
