# Generated by Django 4.1 on 2022-09-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_instructionimages_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='step',
            new_name='order',
        ),
    ]
