# Generated by Django 4.1 on 2022-10-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_instruction_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='instruction_order',
            new_name='id',
        ),
    ]
