# Generated by Django 4.1 on 2022-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_step_instruction_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='order',
            new_name='instruction_order',
        ),
        migrations.AlterField(
            model_name='instructionimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
